apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P3460662649363533
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: latency-hunter
      defaultBucket: network-telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token-change-me-in-production
